### ISSUE TITLE
parse error near `\n'

### ISSUE THREAD

**Issue by ghost** [jez/starter-zshrc#1]
Greetings.  I attempted to install (ie, copy) this starter file over with your instructions, then entered `zsh`.

I got the following error:

`/home/yautweh/.zshrc:6: parse error near```\n'`

I have the latest versions of zsh, oh-my-zsh _and_ zsh-syntax-highlighting.  `yautweh` is a user with sudo privs via `sudoers`.

(Thank you  --T)

**Comment by ghost** [comment]
Ahh, I see the problem.

You used the url `https://github.com/jez/starter-zshrc/blob/master/zshrc.zsh`.
I added `-L` to the given `curl` command, but still did not work.

I ended up pulling it directly from Raw.
`curl https://raw.githubusercontent.com/jez/starter-zshrc/master/zshrc.zsh`

That worked.

Cheers.  --T

**Comment by jez** [comment]
Oh good call, that's my bad. I'll fix up the README, thanks!
